[profile.default]
src = "src"
out = "out"
libs = ["lib"]
odyssey = true

[profile.default.fuzz]
runs = 100

[profile.ci.fuzz]
runs = 100000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
